### ISSUE TITLE
Issues with header files.

### ISSUE THREAD

**Issue by mohamedhaddi** [cacharle/c_formatter_42.vim#1]
Hi!

When running the plugin on a `.h` file, some norm rules aren't applied or aren't well applied, e.g.:

For the following file, this is how it gets formatted after running the `:CFormatter42` command:

```c
   13 #ifndef CUB3D_H
   14 #define CUB3D_H
   15
   16 #include <mlx.h>
   17
   18 typedef struct  s_data
   19 {
   20     void            *img;
   21     char            *addr;
   22     int         bits_per_pixel;
   23     int         line_length;
   24     int         endian;
   25 }               t_data;
   26
   27 #endif
```

Though here we've got some norm errors according to the Norminette:
```
Error (line 14): wrong number of spaces in preprocessor indentation
Error (line 16): wrong number of spaces in preprocessor indentation
Error (line 18): Struct s_data bad aligned
```
And thus this is how it should be formatted:

```c
   13 #ifndef CUB3D_H
   14 # define CUB3D_H
   15
   16 # include <mlx.h>
   17
   18 typedef struct  s_data
   19 {
   20     void        *img;
   21     char        *addr;
   22     int         bits_per_pixel;
   23     int         line_length;
   24     int         endian;
   25 }               t_data;
   26
   27 #endif
```

As a temporary fix, is there a way to disable the plugin on header files? Since I'd like to keep using the format-on-save option.

Thanks!

**Comment by cacharle** [comment]
Related issues:
- https://github.com/dawnbeen/c_formatter_42/issues/4
- https://github.com/dawnbeen/c_formatter_42/issues/3

**Comment by cacharle** [comment]
Since then, https://github.com/dawnbeen/c_formatter_42/issues/4 has been closed and other bug fix have been made. https://github.com/dawnbeen/c_formatter_42/issues/3 is still pending tho.

**Comment by cacharle** [comment]
https://github.com/dawnbeen/c_formatter_42/issues/3 is fixed.

Altho a new only has a arise: https://github.com/dawnbeen/c_formatter_42/issues/9

All the problems pointed out by your issue have been fixed so I'm closing it.

If you find more bugs which don't concern this plugin directly (the bug you referenced are from [c_formatter_42](https://github.com/dawnbeen/c_formatter_42)) please post them there.

**Comment by cacharle** [comment]
By the way, I really appreciate the bug report for this project since I'm not currently working on any C school project. So I don't use this formatter myself at the moment and it's hard to find the bugs.

**Comment by mohamedhaddi** [comment]
Thanks a lot, I will make sure to report any new bugs in the right repository, thank you for keeping this project alive!
